# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarningEnvironmentRecord',
            fields=[
                ('warning_ID', models.AutoField(primary_key=True, serialize=False)),
                ('warning_Temperature', models.FloatField(verbose_name='温度检测')),
                ('warning_Humidity', models.FloatField(verbose_name='湿度检测')),
                ('warning_CarbonDioxide', models.FloatField(verbose_name='二氧化碳检测')),
                ('warning_PM', models.FloatField(verbose_name='PM2.5检测')),
            ],
        ),
        migrations.CreateModel(
            name='WarningFightingRecord',
            fields=[
                ('warning_ID', models.AutoField(primary_key=True, serialize=False)),
                ('warning_CH4', models.FloatField(blank=True, null=True, verbose_name='甲烷检测')),
                ('warning_Smog', models.FloatField(blank=True, null=True, verbose_name='烟雾检测')),
                ('warning_Fire', models.FloatField(blank=True, null=True, verbose_name='火光检测')),
            ],
        ),
        migrations.CreateModel(
            name='WarningHandleRecord',
            fields=[
                ('warning_ID', models.AutoField(primary_key=True, serialize=False)),
                ('warning_Person', models.CharField(max_length=30, verbose_name='警告确认人')),
                ('warning_HandleTime', models.DateTimeField(verbose_name='警告确认时间')),
                ('warning_HandleIllustration', models.TextField(default='', verbose_name='解释说明')),
                ('warning_VerifyTime', models.DateTimeField(verbose_name='审核时间')),
                ('warning_VerifyFeedback', models.TextField(default='', verbose_name='审核反馈')),
                ('warning_VerifyPerson', models.CharField(max_length=30, verbose_name='审核人员')),
                ('warning_Level', models.CharField(choices=[('serious', '严重警告'), ('important', '重要警告'), ('general', '一般警告')], max_length=30, verbose_name='报警级别')),
            ],
        ),
        migrations.CreateModel(
            name='WarningRecord',
            fields=[
                ('warning_ID', models.AutoField(primary_key=True, serialize=False)),
                ('warning_SummaryInfo', models.TextField(default='', verbose_name='警报概要信息')),
                ('warning_StartTime', models.DateTimeField(verbose_name='警报开始时间')),
                ('warning_EndTime', models.DateTimeField(verbose_name='警报结束时间')),
                ('warning_Type', models.CharField(choices=[('environment', '环境监测'), ('fighting', '消防监测'), ('security', '安防监测'), ('scene', '场景监测')], max_length=20, verbose_name='报警类型')),
                ('warning_Scene', models.IntegerField(verbose_name='所属场景')),
                ('warning_Equipment', models.CharField(max_length=30, verbose_name='告警设备')),
                ('warning_Content', models.TextField(default='', verbose_name='告警内容')),
                ('warning_State', models.CharField(choices=[('pendingNew', '待处理'), ('pendingApproval', '待审核'), ('auditing', '审核通过'), ('auditFailed', '审核不通过')], max_length=30, verbose_name='告警状态')),
            ],
        ),
        migrations.CreateModel(
            name='WarningSceneRecord',
            fields=[
                ('warning_ID', models.AutoField(primary_key=True, serialize=False)),
                ('warning_Online', models.BooleanField(verbose_name='是否在线')),
            ],
        ),
        migrations.CreateModel(
            name='WarningSecurityRecord',
            fields=[
                ('warning_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='warninghandlerecord',
            name='warning_RecordID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarmMGT.WarningRecord'),
        ),
    ]
