# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logMGT_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_Time', models.DateTimeField(default=datetime.datetime(2019, 7, 5, 15, 25, 33, 198450), null=True, verbose_name='日志时间')),
                ('scene_ID', models.IntegerField(default=0, verbose_name='场景ID')),
                ('scene_IDCode', models.CharField(default='', max_length=10, verbose_name='场景识别码')),
                ('log_Type', models.IntegerField(choices=[(1, '状态变化'), (2, '设备操作'), (3, '数据变化'), (4, '门禁开锁')], default=3, verbose_name='日志类型')),
                ('log_Detail', models.CharField(default='', max_length=50, verbose_name='日志描述')),
            ],
        ),
        migrations.CreateModel(
            name='logMGT_Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_ID', models.IntegerField(default=0, verbose_name='场景ID')),
                ('scene_IDCode', models.CharField(default='', max_length=10, verbose_name='场景识别码')),
                ('device_ID', models.IntegerField(default=0, verbose_name='设备ID')),
                ('device_Status', models.IntegerField(choices=[(1, '上线'), (2, '下线'), (3, '')], default=3, verbose_name='设备状态')),
                ('user_ID', models.IntegerField(default=0, verbose_name='用户ID')),
                ('device_Control', models.CharField(default='', max_length=50, verbose_name='设备控制')),
                ('user_Action', models.CharField(default='', max_length=50, verbose_name='用户行为')),
            ],
        ),
    ]
