# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInformation',
            fields=[
                ('video_ID', models.AutoField(primary_key=True, serialize=False)),
                ('video_IdentifyingCode', models.IntegerField()),
                ('video_Name', models.CharField(max_length=30, verbose_name='视频名称')),
                ('video_describe', models.TextField(default='', verbose_name='描述')),
                ('video_StreamAddress', models.URLField(verbose_name='流地址')),
            ],
        ),
    ]
