# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessAPP_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_Time', models.DateTimeField(default=datetime.datetime(2019, 7, 5, 15, 25, 33, 193488), null=True, verbose_name='申请时间')),
                ('user_ID', models.IntegerField(default=0, verbose_name='用户ID')),
                ('scene_ID', models.IntegerField(default=0, verbose_name='场景ID')),
                ('apply_Detail', models.CharField(default='', max_length=50, verbose_name='申请说明')),
                ('apply_Status', models.IntegerField(choices=[(1, '待审批'), (2, '已通过'), (3, '已拒绝')], default=1, verbose_name='审批状态')),
                ('approval_Time', models.DateTimeField(default='', null=True, verbose_name='审批时间')),
                ('approval_User', models.IntegerField(default=0, verbose_name='审批人')),
                ('approval_Detail', models.CharField(default='', max_length=50, verbose_name='审批反馈')),
            ],
        ),
    ]
