# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_ID', models.IntegerField(default=0, verbose_name='场景id')),
                ('scene_IDCode', models.CharField(default='', max_length=10, verbose_name='场景识别码')),
                ('scene_Name', models.CharField(default='', max_length=30, verbose_name='场景名称')),
                ('scene_Password', models.CharField(default='', max_length=10, verbose_name='场景密码')),
                ('scene_LinkTime', models.DateTimeField(default=datetime.datetime(2019, 7, 5, 15, 25, 33, 199448), verbose_name='场景接入时间')),
                ('scene_Status', models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=1, verbose_name='场景状态')),
                ('scene_CreateTime', models.DateTimeField(default=datetime.datetime(2019, 7, 5, 15, 25, 33, 199448), verbose_name='场景创建时间')),
                ('scene_DeviceNum', models.IntegerField(default=0, verbose_name='场景设备的数量')),
                ('scene_Priority', models.IntegerField(choices=[(1, '高'), (2, '中'), (3, '低')], default=1, verbose_name='场景优先级')),
            ],
        ),
        migrations.CreateModel(
            name='Scene_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_GatewayStatus', models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=1, verbose_name='场景网关状态')),
                ('date_UpdateTime', models.DateTimeField(default=datetime.datetime(2019, 7, 5, 15, 25, 33, 199919), verbose_name='数据更新时间')),
                ('device_OnlineRatio', models.FloatField(default='', verbose_name='设备在线比例')),
                ('scene_Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sceneMGT.Scene_Management')),
            ],
        ),
    ]
